version: "3.9"

services:
  db:
    image: mysql
    restart: always
    container_name: veryable-db
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-data:/var/lib/mysql
      - db-config:/etc/mysql
  app:
    build: .
    image: veryable:base
    entrypoint: /bin/sh ./scripts/entrypoint.sh
    container_name: veryable-app
    environment:
      DATABASE_URL: $DOCKER_DATABASE_URL #overrides the local database url environment
    links:
      - db
    depends_on:
      - db
volumes:
  db-data:
  db-config: