version: "3.9"

services:
  db:
    image: mysql
    restart: always
    container_name: veryable-db
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-data:/var/lib/mysql
      - db-config:/etc/mysql
volumes:
  db-data:
  db-config: